version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: on-failure
    ports:
      - "443:443"
    volumes:

    depends_on:

  wordpress:

  mariadb: